# Generated by Django 5.2.4 on 2025-11-29 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the notice', max_length=200)),
                ('content', models.TextField(help_text='Detailed content of the notice')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the notice', max_length=10)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('event', 'Event'), ('maintenance', 'Maintenance'), ('holiday', 'Holiday'), ('announcement', 'Announcement'), ('other', 'Other')], default='announcement', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Optional image for the notice', null=True, upload_to='campus_updates/')),
                ('is_published', models.BooleanField(default=True, help_text='Whether the notice is visible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Date when the notice expires', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campus Update',
                'verbose_name_plural': 'Campus Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
