# Generated by Django 5.2.4 on 2025-11-29 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='noti_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of_noti',
            field=models.CharField(choices=[('comment_answer', 'comment_answer'), ('question_comment', 'question_comment'), ('community_message', 'community_message'), ('question_edit', 'question_edit'), ('question_reopen_voted', 'Question ReOpen Voted'), ('question_suggested_edit', 'Question Suggested Edit'), ('NEW_ANSWER', 'New_Answer'), ('community_join_request', 'Community Join Request')], default='', max_length=30),
        ),
    ]
