# Generated by Django 5.2.8 on 2025-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_alter_profile_full_name_alter_profile_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="password_change_required",
            field=models.BooleanField(default=True),
        ),
    ]
