# Generated by Django 5.2.4 on 2025-11-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_profile_password_change_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=20),
        ),
    ]
