# Generated by Django 5.2.8 on 2025-11-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0006_remove_job_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="profile",
            name="prefered_technologies",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
