# Generated by Django 5.2.4 on 2025-11-23 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('qa', '0003_postshare_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='community',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='community.community'),
        ),
        migrations.AddField(
            model_name='question',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='community.community'),
        ),
    ]
